### ISSUE TITLE
NULL result from engine.stream() after upgrade from 4.0.0 to 4.1.0

### ISSUE THREAD

**Issue by bcomisky** [jenetics/jenetics#318] opened 2018-02-15 22:12 UTC
I just swapped in the Jenetics 4.1.0 libraries for version 4.0.0.  I'm now getting a NULL result here occasionally (random seed dependent) when I use `Limits.byPopulationConvergence()`:

```java
        final EvolutionResult<DoubleGene, Double> result = engine.stream()
                .limit(Limits.byPopulationConvergence(.03))
                .limit(maxGeneration)
                .peek(this::logger)
                .collect(toBestEvolutionResult());
```
If I reduce the argument to `Limits.byPopulationConvergence()` enough, it runs every time.  This is a toy problem that may be converged at the first generation.  Similar problems with more diversity don't have this problem.

**Comment by jenetics** [comment] 2018-02-16 07:21
Can you also give me your `Problem` definition. I tried it with 
```java
final Problem<Double, DoubleGene, Double> problem = Problem.of(
	d -> d,
	Codecs.ofScalar(DoubleRange.of(0, 1))
);
```
but I couldn't reproduce the error.

**Comment by bcomisky** [comment] 2018-02-16 16:25
I'll see if I can strip down my code to something more simple that still replicates the error.

**Comment by bcomisky** [comment] 2018-02-18 22:02
Taking it to an extreme, try making the fitness return a constant:

```final Problem<Double, DoubleGene, Double> problem = Problem.of(
	d -> 1.0,
	Codecs.ofScalar(DoubleRange.of(0, 1))
);
```

in 4.1.0 using `Limits.byPopulationConvergence()` I get `null` when collecting the best evolution result.  If I use 4.0.0 it works, or if I just limit by max generation it works in either 4.0.0 or 4.1.0.

**Comment by jenetics** [comment] 2018-02-19 10:20
I slightly changed the behavior of the `EvolutionStream.limit(Predicate)` method in version 4.1. If the limit predicate is fulfilled for the initial population, no evolution is performed at all. In such a case, the _problem_ can be represented by
```java
final EvolutionResult<DoubleGene, Double> result = engine.stream()
    .limit(0)
    .collect(toBestEvolutionResult());
```
Writing it this way it's clear, I think, that you can't collect a result. So `null` may be a sensible return value. If you write it with a limiting predicate, the null becomes _less_ obvious. Although the initial population satisfy the termination predicate and the _size_ of the evolution stream is 0.
```java
final EvolutionResult<DoubleGene, Double> result = engine.stream()
    .limit(Limits.byPopulationConvergence(0.03))
    .collect(toBestEvolutionResult());
```
But if you replace the convergence predicate with 
```java
final EvolutionResult<DoubleGene, Double> result = engine.stream()
    .limit(Limits.byFixedGeneration(0))
    .collect(toBestEvolutionResult());
```
the returned `null` value looks _correct_ again.

It is also not possible to just return the initial population in this case. If I set the limit of the stream to 0, I would expect a stream length of 0 as well.

```java
final long length = engine.stream()
    .limit(Limits.byFixedGeneration(0))
    .count();
assert length == 0L;
```

If I return the initial population in such cases, the stream length would be 1.

I'm not sure what's the correct or least surprising result in this cases. Any thoughts about this?

**Comment by jenetics** [comment] 2018-02-19 11:16
A _workaround_ would be:
```java
final EvolutionResult<DoubleGene, Double> result = engine.stream()
    .limit(
        Limits.<Double>byPopulationConvergence(0.03).or(
        Limits.byFixedGeneration(1)))
    .collect(toBestEvolutionResult());
```
The length of the evolution string is at least 1.

**Comment by bcomisky** [comment] 2018-02-19 15:08
Thanks for the workaround.  My expectation (not thinking from the stream processing perspective) would have been either:

-  The convergence criteria is tested after evolution is performed, so the generation is always incremented by one, OR
- If the convergence criteria is checked first and is satisfied before any evolution takes place, then the starting population is returned.

Consider a case using your original fitness function `d -> d` and `Limits.byFitnessThreshold()'.  A "lucky" random seed could achieve the threshold in the initial random population, but a null result would be returned.  I could see this being a rare and surprising result that would be difficult to test for and anticipate ahead of time.

**Comment by jenetics** [comment] 2018-02-19 16:19
I will change all predicates in the `Limits` class, that the evolution stream size is at least one. An exception would be the ` Limits.byFixedGeneration` termination strategy. For `Limits.byFixedGeneration(0)`, a `null` result is expected.

It is also necessary to better document this edge cases.

**Comment by jenetics** [comment] 2018-02-19 18:45
Merged into r4.2.0 branch.

**Closed by jenetics** 2018-02-19 18:45 UTC
Labels: bug, manual
